// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ufpb.domain;

import com.ufpb.domain.Anuncio;
import com.ufpb.domain.AnuncioDataOnDemand;
import com.ufpb.domain.ProdutoDataOnDemand;
import com.ufpb.repository.AnuncioRepository;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AnuncioDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AnuncioDataOnDemand: @Component;
    
    private Random AnuncioDataOnDemand.rnd = new SecureRandom();
    
    private List<Anuncio> AnuncioDataOnDemand.data;
    
    @Autowired
    ProdutoDataOnDemand AnuncioDataOnDemand.produtoDataOnDemand;
    
    @Autowired
    AnuncioRepository AnuncioDataOnDemand.anuncioRepository;
    
    public Anuncio AnuncioDataOnDemand.getNewTransientAnuncio(int index) {
        Anuncio obj = new Anuncio();
        setDescricao(obj, index);
        setNome(obj, index);
        setValor(obj, index);
        return obj;
    }
    
    public void AnuncioDataOnDemand.setDescricao(Anuncio obj, int index) {
        String descricao = "descricao_" + index;
        obj.setDescricao(descricao);
    }
    
    public void AnuncioDataOnDemand.setNome(Anuncio obj, int index) {
        String nome = "nome_" + index;
        obj.setNome(nome);
    }
    
    public void AnuncioDataOnDemand.setValor(Anuncio obj, int index) {
        String valor = "valor_" + index;
        obj.setValor(valor);
    }
    
    public Anuncio AnuncioDataOnDemand.getSpecificAnuncio(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Anuncio obj = data.get(index);
        Long id = obj.getId();
        return anuncioRepository.findOne(id);
    }
    
    public Anuncio AnuncioDataOnDemand.getRandomAnuncio() {
        init();
        Anuncio obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return anuncioRepository.findOne(id);
    }
    
    public boolean AnuncioDataOnDemand.modifyAnuncio(Anuncio obj) {
        return false;
    }
    
    public void AnuncioDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = anuncioRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Anuncio' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Anuncio>();
        for (int i = 0; i < 10; i++) {
            Anuncio obj = getNewTransientAnuncio(i);
            try {
                anuncioRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            anuncioRepository.flush();
            data.add(obj);
        }
    }
    
}
