// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ufpb.domain;

import com.ufpb.domain.AnuncioDataOnDemand;
import com.ufpb.domain.AnuncioIntegrationTest;
import com.ufpb.repository.AnuncioRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AnuncioIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AnuncioIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AnuncioIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AnuncioIntegrationTest: @Transactional;
    
    @Autowired
    AnuncioDataOnDemand AnuncioIntegrationTest.dod;
    
    @Autowired
    AnuncioRepository AnuncioIntegrationTest.anuncioRepository;
    
    @Test
    public void AnuncioIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Anuncio' failed to initialize correctly", dod.getRandomAnuncio());
        long count = anuncioRepository.count();
        Assert.assertTrue("Counter for 'Anuncio' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AnuncioIntegrationTest.testFind() {
        Anuncio obj = dod.getRandomAnuncio();
        Assert.assertNotNull("Data on demand for 'Anuncio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Anuncio' failed to provide an identifier", id);
        obj = anuncioRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Anuncio' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Anuncio' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AnuncioIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Anuncio' failed to initialize correctly", dod.getRandomAnuncio());
        long count = anuncioRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Anuncio', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Anuncio> result = anuncioRepository.findAll();
        Assert.assertNotNull("Find all method for 'Anuncio' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Anuncio' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AnuncioIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Anuncio' failed to initialize correctly", dod.getRandomAnuncio());
        long count = anuncioRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Anuncio> result = anuncioRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Anuncio' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Anuncio' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AnuncioIntegrationTest.testFlush() {
        Anuncio obj = dod.getRandomAnuncio();
        Assert.assertNotNull("Data on demand for 'Anuncio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Anuncio' failed to provide an identifier", id);
        obj = anuncioRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Anuncio' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAnuncio(obj);
        Integer currentVersion = obj.getVersion();
        anuncioRepository.flush();
        Assert.assertTrue("Version for 'Anuncio' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AnuncioIntegrationTest.testSaveUpdate() {
        Anuncio obj = dod.getRandomAnuncio();
        Assert.assertNotNull("Data on demand for 'Anuncio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Anuncio' failed to provide an identifier", id);
        obj = anuncioRepository.findOne(id);
        boolean modified =  dod.modifyAnuncio(obj);
        Integer currentVersion = obj.getVersion();
        Anuncio merged = anuncioRepository.save(obj);
        anuncioRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Anuncio' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AnuncioIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Anuncio' failed to initialize correctly", dod.getRandomAnuncio());
        Anuncio obj = dod.getNewTransientAnuncio(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Anuncio' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Anuncio' identifier to be null", obj.getId());
        try {
            anuncioRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        anuncioRepository.flush();
        Assert.assertNotNull("Expected 'Anuncio' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AnuncioIntegrationTest.testDelete() {
        Anuncio obj = dod.getRandomAnuncio();
        Assert.assertNotNull("Data on demand for 'Anuncio' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Anuncio' failed to provide an identifier", id);
        obj = anuncioRepository.findOne(id);
        anuncioRepository.delete(obj);
        anuncioRepository.flush();
        Assert.assertNull("Failed to remove 'Anuncio' with identifier '" + id + "'", anuncioRepository.findOne(id));
    }
    
}
