// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ufpb.domain;

import com.ufpb.domain.UsuarioDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UsuarioDataOnDemand_Roo_Configurable {
    
    declare @type: UsuarioDataOnDemand: @Configurable;
    
}
